FROM mcr.microsoft.com/windows/servercore:10.0.14393.2906

LABEL maintainer "Enouvo IT Solutions"

ARG SQL_COLLATION=SQL_Latin1_General_CP1_CI_AS

# Download Links:
ENV sql_express_download_url "https://go.microsoft.com/fwlink/?linkid=829176"

ENV sa_password="_" \
    attach_dbs="[]" \
    ACCEPT_EULA="_" \
    sa_password_path="C:\ProgramData\Docker\secrets\sa-password"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# make install files accessible

WORKDIR /

VOLUME C:/Sql/Backup
VOLUME C:/Sql/UserDbs

RUN Invoke-WebRequest -Uri $env:sql_express_download_url -OutFile sqlexpress.exe; \
    Start-Process -Wait -FilePath .\sqlexpress.exe -ArgumentList /qs, /x:setup; \
    .\setup\setup.exe /q /ACTION=Install /INSTANCENAME=DOCKERSQL /FEATURES=SQLEngine /UPDATEENABLED=0 /SQLSVCACCOUNT='NT AUTHORITY\System' /SQLSYSADMINACCOUNTS='BUILTIN\ADMINISTRATORS' /TCPENABLED=1 /NPENABLED=0 /IACCEPTSQLSERVERLICENSETERMS /INSTALLSQLDATADIR=C:\Sql /SQLBACKUPDIR=C:\Sql\Backup /SQLUSERDBDIR=C:\Sql\UserDbs /SQLUSERDBLOGDIR=C:\Sql\UserDbs /SQLCOLLATION=$env:SQL_COLLATION; if ($LASTEXITCODE -ne 0) { throw ('SQL Install failed with exit code {0}' -f $LASTEXITCODE) }; \
    Remove-Item -Recurse -Force sqlexpress.exe, setup

RUN stop-service MSSQL`$DOCKERSQL; set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql14.DOCKERSQL\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpdynamicports -value '' ; set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql14.DOCKERSQL\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpport -value 1433 ; set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql14.DOCKERSQL\mssqlserver\' -name LoginMode -value 2 ;

COPY start.ps1 /

CMD .\start -sa_password $env:sa_password -ACCEPT_EULA $env:ACCEPT_EULA -attach_dbs \"$env:attach_dbs\" -Verbose
